language: java
jdk:
  - oraclejdk8
  - oraclejdk9

env:
  - GRADLE_OPTS="-Xmx512m"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew coveralls

notifications:
  slack:
    - secure: "1syrpHg4QvkqcpOK2ov14IerjcFZpA5TzqKsK2prnI50VvgJq61QJDIvhXv1k/v5UJD9J+AvkvY/HbXTGMqXWtoR5xiO/CnkE7L/NC6w5zH5axcONVC1qqZ2/75DgmsyFEx4+5EgLOvU6wq2lVl1D3oQqRDz6fL8B0Ls14ITdfwK3rTTXiaFh+JyukfCYvoC1QBr0kj4xS6PFuCueUqCrv27v/5o0tmzEx7Mx/oomRh21dHCPs5fFIhxWFDHZrDy68cYVCXmrlbA3AZiTxwv8btjv2+1RPcfsrROL7C+1pt2ylvuR15I7lgaHBPN0HjJ7GsidEqBmhYbyR9BGhTxnfHF9euLPkkmB5HqI67QIa/qdgv7QhUicNV1ROUOe7oDsAkjQVKgFDZhuMR7l9lDdZ1jDgMlhnX3lbwxjkPIepC55uYgOvfkLLr/od7g3aPo4peMwna+YgACgeYCJaE+aw3iZt+DbCBscpcEel+c9/h8vg49NEdCV60gNNjmbI/uKB1XCdDE6/DLmuQrBHZQEyUwawb9Fo9OOdHcmeqobEj4XS+2I/Hjue3YiRZ4VcdKzFVjXAVBshCueYfFlwkE6bbia1gVmvQ43QM0fWCEJhXl6wDA7DVJx6WLSlK+QCSZTPe38y5Gad1ufz9Qv0EvpVuIbT1KnoZ5XFE+Aib5yX4="
