language: java
jdk:
  - oraclejdk8
  - openjdk7

env:
  - GRADLE_OPTS="-Xmx512m"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew coveralls

notifications:
  slack:
    - secure: "YnbjBFZ2mLKo6uPnKwWP0XwS8frSACrVr3RnHRdS/UGxAlndJwb5N7SPTCF2RsmC7ZBDal3C9PMUwteMvwKu6IibTt/YClFnrKnk/hpJF2zoockT5JTj46umQ0LQS7D0bGcJBxPmdKbxC9IcxbXYeYNkSu0iwBc6aR1xLvwO9BEHTcDV7Kv8g/VBt8vmPU+a0w8OsWwlxYjo6SAvnGyQ2/TqmSdDjqyhwfX2sUq+11iNwTt9Cp2ECK8077aCXUIhoUOfGbPsgE8cKU2OiDddLnpJv5c50Mfs2YpDaTTDys6nq9pd+dG74UY4NdU4ldWYC7lPl5J/i+AWVriXBi90XX2FZ4SDXFVrOCm4+4b4tbVvfi7Dt9alu4PwVt5TAjOOyTzbK3xYO9Gwvfa+BC0lgpdzwMPCagrxR1O/M0ZM1lt9/YlAcCvjbYuyZmYQ0ZgVU8JvBS2rpWcNNtoIH1vvsmXpxt/qoKQba/5t0cf/0uSNnyj3xtMv4mEiwue5e7Egn4Edy9LUmkW07fGyPVW87oGCdtQ/6XObfNfrycPF/HD3LLL5JIFM0XcGWZAg4MPYijV1RiY84VbBB7fM6axwMv2KNYVF2J89ioaTMdX7+gphYDnG5fLcZWA0G7nQ8vgNvHWl6t7FnorsZorAemOq6fjI/A0O/3/7BaluuaY/3QU="
